Traceback (most recent call last):
  File "run-tests.py", line 6, in <module>
    from unittests import *
  File "/home/dangelo/mounted_parts/sda1/Courses/coursera/ibm_ai_workflow/6_ai_in_production/week_1/case_study/unittests/__init__.py", line 29, in <module>
    from ModelTests import *
  File "/home/dangelo/mounted_parts/sda1/Courses/coursera/ibm_ai_workflow/6_ai_in_production/week_1/case_study/unittests/ModelTests.py", line 8, in <module>
    from model import *
  File "/home/dangelo/mounted_parts/sda1/Courses/coursera/ibm_ai_workflow/6_ai_in_production/week_1/case_study/model.py", line 8, in <module>
    from logger import *
  File "/home/dangelo/mounted_parts/sda1/Courses/coursera/ibm_ai_workflow/6_ai_in_production/week_1/case_study/logger.py", line 22, in <module>
    from model import get_model_version
ImportError: cannot import name 'get_model_version' from 'model' (/home/dangelo/mounted_parts/sda1/Courses/coursera/ibm_ai_workflow/6_ai_in_production/week_1/case_study/model.py)
